
# Workflow

# Should Have Name
name: Hello
# We should specify when it should run
on:  
  workflow_dispatch: 

# Jobs ( there can be multiple jobs)
# Should be inside the workflow
jobs:
# first job
  say_hello:
# creates a temporary container  
    runs-on: ubuntu-latest
# Steps   
# Should be insite the job this steps will have a name and rub will have the commands
    steps:
      - name: say hello to everyone
        run: echo"hello doato"
# Actions

# Should be inside the Steps





